import { useState } from 'react'
import Button from './Button'

const empty = { title: '', description: '', category: '', price: '', deliveryDays: '', revisions: 1, status: 'active', terms: '' }

export default function CommissionForm({ commission, onSubmit, onCancel, busy = false }) {
  const [form, setForm] = useState(commission || empty)
  const [error, setError] = useState('')
  function update(name, value) { setForm((current) => ({ ...current, [name]: value })) }
  async function submit(event) { event.preventDefault(); setError(''); try { await onSubmit({ ...form, price: Number(form.price), deliveryDays: Number(form.deliveryDays), revisions: Number(form.revisions) }); if (!commission) setForm(empty) } catch (submitError) { setError(submitError.message) } }
  return <form className="workspace-form" onSubmit={submit}><div className="form-two-columns"><label htmlFor="commission-title">Título<input id="commission-title" required value={form.title} onChange={(event) => update('title', event.target.value)} /></label><label htmlFor="commission-category">Categoría<input id="commission-category" required value={form.category} onChange={(event) => update('category', event.target.value)} /></label></div><label htmlFor="commission-description">Descripción<textarea id="commission-description" required minLength="10" value={form.description} onChange={(event) => update('description', event.target.value)} /></label><div className="form-two-columns"><label htmlFor="commission-price">Precio (USD)<input id="commission-price" type="number" min="1" required value={form.price} onChange={(event) => update('price', event.target.value)} /></label><label htmlFor="commission-days">Días de entrega<input id="commission-days" type="number" min="1" required value={form.deliveryDays} onChange={(event) => update('deliveryDays', event.target.value)} /></label></div><div className="form-two-columns"><label htmlFor="commission-revisions">Revisiones<input id="commission-revisions" type="number" min="0" required value={form.revisions} onChange={(event) => update('revisions', event.target.value)} /></label><label htmlFor="commission-status">Estado<select id="commission-status" value={form.status} onChange={(event) => update('status', event.target.value)}><option value="active">Activa</option><option value="paused">Pausada</option></select></label></div><label htmlFor="commission-terms">Términos<textarea id="commission-terms" required minLength="10" value={form.terms} onChange={(event) => update('terms', event.target.value)} /></label>{error && <p className="form-message form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="submit" loading={busy}>{commission ? 'Guardar cambios' : 'Agregar tarifa'}</Button>{commission && <Button type="button" variant="outline" onClick={onCancel}>Cancelar</Button>}</div></form>
}
