export const ART_CATEGORIES = [
  'Ilustración Digital',
  'Diseño de Personajes',
  'Concept Art',
  'Modelado 3D',
  'Pixel Art',
  'Modelos VTuber',
  'Live2D',
  'Arte para Videojuegos',
  'Motion Graphics',
  'Arte Vectorial',
  'Cómic y Manga Digital',
  'Voxel Art',
  'Animación 2D/3D',
  'UI/UX Design',
  'Arte Generativo',
  'Retrato / Semirrealismo',
  'Fantasía / Sci-Fi',
  'Chibi / Anime',
]
